### ISSUE TITLE
[fix] PostGIS 설치 및 설정 이슈

### ISSUE THREAD

**Issue by sensesis** [project-Rebo/rebo-infra#9]
### 🚀 Summary

##문제 상황
- PostgreSQL 데이터베이스에 PostGIS 확장이 설치되어 있지 않아 공간 함수 사용 시 오류 발생
- `type "geography" does not exist` 에러 발생

## 원인
- PostgreSQL 데이터베이스에 PostGIS 확장이 설치되지 않음
- Docker 컨테이너에서 PostGIS 확장을 활성화하지 않음

## 해결 방법
1. Docker Compose 파일에서 PostGIS 이미지 사용
   ```yaml
   services:
     db:
       image: postgis/postgis:16-3.4
       # ... 기타 설정 ...
   ```

2. 로컬 환경과 Docker 컨테이너의 중복 설정 제거
   - `rebo-infra/db/init/init.sql` 파일에서 `CREATE EXTENSION IF NOT EXISTS postgis;` 명령어 제거
   - PostGIS 이미지를 사용하므로 별도의 확장 설치 명령어 불필요

## 참고 사항
- PostGIS 이미지를 사용하면 별도의 확장 설치 없이 공간 함수 사용 가능
- 로컬 환경과 Docker 컨테이너의 설정 중복을 피하여 유지보수성 향상

---

### 📝 To Do

- [ ] `rebo-infra/db/init/init.sql` 파일에서 `CREATE EXTENSION IF NOT EXISTS postgis;` 명령어 제거
- [ ] Docker Compose 파일에서 `postgis/postgis:16-3.4` 이미지 사용 확인
- [ ] 애플리케이션 재시작하여 PostGIS 관련 오류 해결 확인

---
